# Generated by Django 5.1.3 on 2024-11-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
